#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx', git: 'git://github.com/opscode-cookbooks/nginx.git'
cookbook 'unicorn', path: "site-cookbooks/unicorn"
cookbook 'rails', path: "site-cookbooks/rails"